# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Trenchman < Formula
  desc "A standalone nREPL/prepl client written in Go, heavily inspired by Grenchman"
  homepage "https://github.com/athos/trenchman"
  version "0.3.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/athos/trenchman/releases/download/v0.3.0/trenchman_0.3.0_macos_amd64.tar.gz"
      sha256 "98840597abffff3be9dbb742780eaa9f5b912b548dd596419fc6a84a0d552314"
    end
    if Hardware::CPU.arm?
      url "https://github.com/athos/trenchman/releases/download/v0.3.0/trenchman_0.3.0_macos_arm64.tar.gz"
      sha256 "50cd6e742d1dbce0592e6b817b8ab1a518cb193aee67c98086c6f9234781528c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/athos/trenchman/releases/download/v0.3.0/trenchman_0.3.0_linux_amd64.tar.gz"
      sha256 "0c46bfdd369c60584d3ff2669d5421b30c5c244d92606782655de551baf912b4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/athos/trenchman/releases/download/v0.3.0/trenchman_0.3.0_linux_arm64.tar.gz"
      sha256 "3ff7223a81b8161b6196d107a0249a456c1cf887c20cb2a0d1f0fb0af086afd5"
    end
  end

  def install
    bin.install "trench"
  end

  test do
    system "#{bin}/trench --version"
  end
end
